name: Run Go Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: arc-runner-localagent
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: docker-practice/actions-setup-docker@master
      timeout-minutes: 12
    - run: |
        set -x

        docker version

        docker run --rm hello-world
    - name: Run tests
      run: |
        sudo apt-get update && sudo apt-get install -y make
        make tests
    #sudo mv coverage/coverage.txt coverage.txt
    #sudo chmod 777 coverage.txt

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
